### ISSUE TITLE
Cannot redefine property: MaterialModule

### ISSUE THREAD

**Issue by mpicciolli** [DevWurm/hello-electron#1] opened 2016-12-23 15:47 UTC
Hi,

I would like to add angular Material 2 in your project, but i have thise error : 

`Uncaught TypeError: Cannot redefine property: MaterialModule__webpack_require__.d @ bootstrap f110f6a…:111(anonymous function) @ index.js:3__webpack_require__ @ bootstrap f110f6a…:52(anonymous function) @ main.bundle.js:50606__webpack_require__ @ bootstrap f110f6a…:52(anonymous function) @ app.module.ts:22__webpack_require__ @ bootstrap f110f6a…:52(anonymous function) @ main.bundle.js:53858__webpack_require__ @ bootstrap f110f6a…:52(anonymous function) @ main.bundle.js:83390__webpack_require__ @ bootstrap f110f6a…:52webpackJsonpCallback @ bootstrap f110f6a…:23(anonymous function) @ main.bundle.js:1`

I follow the getting started instructions  @(https://material.angular.io/guide/getting-started) like this :

npm install --save @angular/material and Import the Angular Material NgModule
 
In app.module.ts
`import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { MaterialModule } from '@angular/material';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    MaterialModule.forRoot()
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
`

**Comment by DevWurm** [comment] 2016-12-24 14:47
Hi :)

I tested a bit and found out, that it works until version `2.0.0-alpha.11` of `@angular/material`. So I recommend using this version, until the problem is fixed.

I created an [issue at the Material2 project](https://github.com/angular/material2/issues/2398). It seems, like being a general problem when using Material2 in a Node.js environment, because [a similar issue also occurs with angular-universal](https://github.com/angular/universal-starter/issues/266).

If you are interested in a bigger project, which uses Angular Material 2 in Electron, you can have a look at [Electron-Microscope](https://github.com/Electron-Microscope/electron-microscope), which we built two months ago.

**Comment by DevWurm** [comment] 2016-12-24 14:49
I may close this issue because the problem is identified and can not be solved by this project and we found a workaround. Feel free to comment, if you have some more issues regarding this problem and I will reopen it.

**Closed as completed by DevWurm** 2016-12-24 14:49 UTC
